MyFirstEShop/Models/DatabaseModels/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstEShop.Models.DatabaseModels
{
    public class Ticket
    {
        public int Id { get; set; }

        public int UserId { get; set; }

        public string Subject { get; set; }

        public string UserQuestion { get; set; }

        public string AdminAnswer { get; set; }

        public DateTime UserSendQuestionDateTime { get; set; }

        public DateTime AdminAnswerDateTime { get; set; }

        #region Navigation Property

        public User User { get; set; }

        #endregion
    }
}

MyFirstEShop/Models/DatabaseModels/UserSetting.cs
using System.IO;

namespace MyFirstEShop.Models.DatabaseModels
{
    public class UserSetting
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool ConfirmEmail { get; set; }
        public bool ConfirmPhoneNumber { get; set; }
        
        public bool TowFactorAthurizeEnable { get; set; }

        #region Navigation Property

        public User UserInfo { get; set; }

        #endregion
    }
}

MyFirstEShop/Models/ViewModels/TicketViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MyFirstEShop.Models.ViewModels
{
    public class TicketViewModel
    {

        public int MessageId { get; set; }
        public int UserId { get; set; }       
        
        [Required(ErrorMessage = "لطفا موضوع را وارد نماید")]
        [Display(Name = "موضوع")]
        [MaxLength(50)]
        public string Subject { get; set; }

        [Required(ErrorMessage = "لطفا متن درخواست خود را وارد نماید")]
        [Display(Name = "متن درخواست")]
        public string UserQuestion { get; set; }

        [Required(ErrorMessage = "لطفا پاسخ درخواست خود را وارد نماید")]
        [Display(Name = "پاسخ درخواست")]
        public string AdminAnswer { get; set; }
        
        [Display(Name = "تاریخ ثبت تیکت")]
        public DateTime UserSendQuestionDateTime { get; set; }

        [Display(Name = "تاریخ پاسخ به تیکت")]
        public DateTime AdminAnswerDateTime { get; set; }

    }
}

MyFirstEShop/Controllers/TicketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyFirstEShop.Attributes;
using MyFirstEShop.Models.ViewModels;
using MyFirstEShop.Repositories;

namespace MyFirstEShop.Controllers
{
    [Authorize]
    [TypeFilter(typeof(CheckUserSecurityStampAttribute))]
    public class TicketController : Controller
    {
        private readonly ITicketRepository ticketRepository;

        public int UserId
        {
            get
            {
                return int.Parse(User.FindFirst("UserId").Value);
            }

        }




        public TicketController(ITicketRepository _ticketRepository)
        {
            ticketRepository = _ticketRepository;
        }

        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SubmitNewTicket(TicketViewModel ticketViewModel)
        {
            ticketRepository.SetNewTicket(ticketViewModel, UserId);
            return RedirectToAction("Index", "Setting");
        }

        public IActionResult ReadTicket(int MID)
        {
            var Ticket = ticketRepository.ReadTicket(UserId, MID);
            return View(Ticket);
        }

    }
}

MyFirstEShop/Views/ViewComponent/UserSetting/ChangeUserInfo.cshtml
@model UserViewModel

@{
    ViewData["Title"] = "تغییر اطلاعات حساب";
}

<h1>تغییر اطلاعات حساب </h1>

<hr />
<div class="row">
    <div class="col-12">
        <form class="CForm" asp-action="ChangeInfo" asp-controller="RegisterUser" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control border-bottom-blue" style="font-size: x-large;" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control border-bottom-blue" style="font-size: x-large;"/>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <textarea asp-for="About" class="form-control border-bottom-blue" style="resize: none; height: 20vh;"></textarea>
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ثبت" class="btn GreenBtn" />
            </div>
            <input asp-for="Id" type="hidden" />
        </form>
    </div>
</div>


@section Scripts {

    <partial name="_ValidationScriptsPartial" />
}

MyFirstEShop/Views/ViewComponent/UserSetting/Dashboard.cshtml
@model UserViewModel

@{
    ViewData["Title"] = "داشبورد";
}

<h1 style="text-align:center;">داشبورد</h1>

<hr />
<div class="row">
    <div class="col-12">
        <form class="CForm" asp-action="Dashboard" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control border-bottom-blue" readonly style="font-size: x-large;" />
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control border-bottom-blue" readonly style="font-size: x-large;" />
                <span asp-for="LastName"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control border-bottom-blue" readonly style="font-size: x-large; direction: ltr;" />
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control border-bottom-blue" readonly style="font-size: x-large; direction: ltr;" />
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <textarea asp-for="About" class="form-control border-bottom-blue" readonly style="resize: none; height: 20vh; font-size: x-large;"></textarea>
            </div>
        </form>
    </div>
</div>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />

}

MyFirstEShop/Views/ViewComponent/UserSetting/Ticket.cshtml
@model IEnumerable<TicketViewModel>


<h3>سلام لطفا برای ارسال پیام به مدیریت بر روی دکمه ی ارسال تیکت کلیک نماید</h3>

<div class="col-12">


    <a asp-area="" asp-action="New" asp-controller="Ticket" class="btn btn-success offset-10"
        style="text-decoration: none;color:white;" >ارسال تیکت</a>

</div>

<div class="col-12 table-responsive mt-3">

    <table>
        <thead>
            <tr>
                <th style="font-size: larger;">#</th>
                <th style="font-size: larger;">تاریخ ایجاد</th>
                <th style="font-size: larger;">موضوع درخواست</th>
                <th style="font-size: larger;">مشاهده ی پرسش و پاسخ</th>
            </tr>
        </thead>

        <tbody>

            @if (Model.Count() != 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MessageId</td>
                        <td>@item.UserSendQuestionDateTime</td>
                        <td>@item.Subject</td>
                        <td>
                            <a asp-area="" asp-action="ReadTicket" asp-controller="Ticket" asp-route-MID=@item.MessageId class="btn btn-info" style="text-decoration: none;color:white;">مشاهد</a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="4">
                        داده ای موجود نمیباشد
                    </td>
                </tr>
            }


        </tbody>

    </table>

</div>