MyFirstEShop/Components/TeacherInfoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using MyFirstEShop.Repositories;

namespace MyFirstEShop.Component
{
    public class TeacherInfoViewComponent : ViewComponent
    {
        private readonly ITeacherRepository teacherRepository;
        public TeacherInfoViewComponent(ITeacherRepository _teacherRepository)
        {
            teacherRepository = _teacherRepository ;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = int.Parse(UserClaimsPrincipal.FindFirst("UserId").Value);

            var teacher = teacherRepository.GetTeacherWithProducts(userId);

            return View("~/Views/ViewComponent/TeacherPanel/TeacherInfoView.cshtml", teacher);
        }
    }
}

MyFirstEShop/Controllers/SettingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyFirstEShop.Attributes;

namespace MyFirstEShop.Controllers
{
    [Authorize]
    [TypeFilter(typeof(CheckUserSecurityStampAttribute))]
    public class SettingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyFirstEShop/Controllers/ShopingListController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstEShop.Repositories;
using Microsoft.AspNetCore.Authorization;
using MyFirstEShop.Attributes;

namespace MyFirstEShop.Controllers
{
    [Authorize]
    [TypeFilter(typeof(CheckUserSecurityStampAttribute))]
    public class ShopingListController : Controller
    {
        private readonly ICartRepository CartRepository;
        private readonly IProductRepository ProductRepository;
        private int UserId
        {
            get
            {
                return int.Parse(User.FindFirst("UserId").Value);
            }
        }

        public ShopingListController(ICartRepository _shopManager, IProductRepository _productManager)
        {
            CartRepository = _shopManager;
            ProductRepository = _productManager;
        }

        public IActionResult Index()
        {
            return View(CartRepository.GetCartViewModel(UserId));
        }

        //[HttpPost]
        public IActionResult AddToCart(int productId)
        {
            var product = ProductRepository.ExistProduct(productId);

            if (product)
            {
                CartRepository.AddProductToCart(productId, UserId);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveItem(int productId)
        {
            CartRepository.RemoveProduct(productId, UserId);
            return RedirectToAction("Index");
        }
    }
}

MyFirstEShop/Areas/Teacher/Views/Shared/_TeacherLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>پنل مدرسین</title>
    <link href="~/lib/bootstrap-v4-rtl-master/dist/css/bootstrap-rtl.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome-free-5.15.3-web/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>

<body class="rtl">

    <div class="user-hide bg-Modal" id="Remove-Product">

        <div class="Box bg-White-Gradian ModalStyle">
            <h1>مدرس گرامی لطفا دقت فرماید</h1>
            <hr />
            <p>لطفا دقت فرماید که با تایید کردن این صفحه شما موارد زیر را قبول کرده اید</p>
            <ul>
                <li>
                    با حذف این دوره وظعیت دوره ی شما به حالت تعلیق تغییر می یابد و سپس با تایید مدیر سایت به حالت غیر فعال تبدیل می شود .
                </li>
                <li>تمامی فیلم های قرار گرفته در این دوره پاک میشود .</li>
                <li>شرکت کنندگان دیگری نمیتوانند وارد این دوره شوند .</li>
                <li>این دوره دیگر در دسترس عموم نخواهد بود .</li>
                <li>
                    این دوره فقط در رسید ها و برای ادمین قابل نمایش خواهد بود
                    و تا زمانی که ادمین و مسئول مربوطه تایید نکند شما نمیتواند آن را بازگردانید .
                </li>


            </ul>
            <form method="post" asp-area="Teacher" asp-controller="Home" asp-action="RemoveProduct">
                <input type="submit" class="btn btn-danger" style="color:white;" value="حذف دوره" />
                <input type="button" class="btn btn-secondary" style="color:white;" onclick="ModalCO()" value="انصراف" />
                <input id="RemoveProduct" type="hidden" name="productId" />
            </form>
        </div>

    </div>

    <header class="row">

        <nav class="col-12 navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">

            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">تمرین دوم - فروشگاه</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <div class="fa-pull-left UserAccountBox" style="">

                            <form asp-area="" asp-controller="RegisterUser" asp-action="Logout" method="post">
                                <img src="https://i.pinimg.com/600x315/80/63/35/8063359effd01b990e653bb32a83485d.jpg"
                                     style="width: 50px; height: 50px; border-radius: 50%; background-position: center; float: left;" />

                                <span> </span>

                                <div class="btn-group">
                                    <button dir="ltr" type="button" class=" dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="border:none;background-color:transparent;margin:5px;">
                                        @(User.FindFirst("FirstName").Value + " " +User.FindFirst("LastName").Value)
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-area="" asp-controller="Setting" asp-action="Index"><i class="fas fa-cogs" style="margin-left:15px;"></i> تنظیمات</a>
                                        @if (bool.Parse(User.FindFirst("IsAdmin").Value))
                                        {
                                            <a asp-area="Admin" asp-action="Index" asp-controller="Home" class="dropdown-item"> ورود به بخش مدیریت</a>
                                        }
                                        @if (bool.Parse(User.FindFirst("IsTeacher").Value))
                                        {
                                            <a asp-area="Teacher" asp-action="Index" asp-controller="Home" class="dropdown-item"><i style="margin-left: 15px;" class="fas fa-chalkboard-teacher"></i> ورود به بخش مدرسین</a>
                                        }
                                        <button class="dropdown-item btn-danger" type="submit"><i class="fas fa-power-off" style="margin-left:15px; color:red;"></i> خروج</button>

                                    </div>
                                </div>

                            </form>

                        </div>


                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">تماس با ما</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShopingList" asp-action="Index"><i class="fas fa-shopping-basket"></i></a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>


    </header>

    <div>

        <main role="main" class="pb-3">

            <div class="container">
                <div class="row">

                    <div class="col-12" style="text-align:center;">

                        <div class="row">
                            <div class="offset-sm-1 col-6 col-md-6  " style=" text-align: right; padding: 20px 0;">
                                @await Component.InvokeAsync("TeacherInfo")
                            </div>

                            <img class="float-left" src="https://i.pinimg.com/600x315/80/63/35/8063359effd01b990e653bb32a83485d.jpg"
                                 style="width:100px; height: 100px; border-radius: 50%; padding: 0; margin-top: 2%;" />
                        </div>

                        <hr class="col-9" style="margin-bottom:0;" />
                        <nav class="col-12">
                            <ul style="list-style: none; margin: 0; padding: 0;">
                                <li class="TeacherBtn"><a asp-area="Teacher" asp-action="Dashboard" asp-controller="Home">داشبورد</a></li>
                                <li class="TeacherBtn"><a asp-area="Teacher" asp-action="AddNewProduct" asp-controller="Home">ثبت محصول جدید</a></li>
                            </ul>
                        </nav>
                    </div>

                    <div class="Group-Panel-Setting col-md-12 Box shadows bg-White-Gradian" style="border-radius: 20px;margin-right:5px;">

                        @RenderBody()

                    </div>

                </div>
            </div>



        </main>
    </div>

    <footer class="bg-white border-top footer text-muted">
        <div class="container">
            <p>Hello World</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>