MyFirstEShop/Areas/Admin/Models/ViewModel/EditUserInfoViewModel.cs
using System.Collections.Generic;
using MyFirstEShop.Models.DatabaseModels;

namespace MyFirstEShop.Areas.Admin.Models.ViewModel
{
    public class EditUserInfoViewModel
    {

        public IEnumerable<Access> UserAccess { get; set; }
        public IEnumerable<Access> AdminAccess { get; set; }
        public User User { get; set; }

    }
}

MyFirstEShop/Areas/Admin/Components/SearchUserViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyFirstEShop.Models.DatabaseModels;
using MyFirstEShop.Areas.Admin.Models.ViewModel;

namespace MyFirstEShop.Areas.Admin.Components
{
    public class SearchUserViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("~/Areas/Admin/Views/UserManagement/SearchUserViewComponent.cshtml", new SearchUserViewModel());
        }

    }
}

MyFirstEShop/Areas/Admin/Controllers/UserManagementController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstEShop.Areas.Admin.Models.ViewModel;
using MyFirstEShop.Attributes;
using MyFirstEShop.Models.DatabaseModels;
using MyFirstEShop.Repositories;
using System.Collections.Generic;

namespace MyFirstEShop.Areas.Admin.Controllers
{

    [Area("Admin")]
    [TypeFilter(typeof(CheckUserSecurityStampAttribute))]
    public class UserManagementController : Controller
    {

        private readonly IUserRepository userRepository;
        private readonly IUserAccessRepository userAccessRepository;

        public int AdminUserId
        {
            get
            {
                return int.Parse(User.FindFirst("UserId").Value);
            }

        }

        public UserManagementController(IUserRepository _userRepository, IUserAccessRepository _userAccessRepository)
        {
            userRepository = _userRepository;
            userAccessRepository = _userAccessRepository;
        }

        #region Search

        // Check Admin Have Access To Edit User Info And Search Him
        [TypeFilter(typeof(CheckAdminAccessAttribute), Arguments = new object[] { Access.CanEditUserInfo })]
        public IActionResult Search()
        {
            return View(new List<User>());
        }

        [TypeFilter(typeof(CheckAdminAccessAttribute), Arguments = new object[] { Access.CanEditUserInfo })]
        public IActionResult Result(SearchUserViewModel searchUserViewModel)
        {
            var user = userRepository.SearchUser(searchUserViewModel);
            return View("Search", user);
        }

        #endregion

        [TypeFilter(typeof(CheckAdminAccessAttribute), Arguments = new object[] { Access.CanSetAccessForUser })]
        public IActionResult EditUserAccess(int userId)
        {
            return View();
        }

        [HttpPost]
        [TypeFilter(typeof(CheckAdminAccessAttribute), Arguments = new object[] { Access.CanSetAccessForUser })]
        public IActionResult EditUserAccess()
        {
            return View();
        }


        [TypeFilter(typeof(CheckAdminAccessAttribute), Arguments = new object[] { Access.CanEditUserInfo })]
        public IActionResult EditUserInfo(int userId)
        {
            var adminAccess = userAccessRepository.GetUserAccess(AdminUserId);
            var userAccess = userAccessRepository.GetUserAccess(userId);
            var user = userRepository.GetUser(userId);
            user.Password = null;

            var ViewModel = new EditUserInfoViewModel()
            {
                AdminAccess = adminAccess,
                UserAccess = userAccess,
                User = user,
            };

            return View(ViewModel);
        }

        [HttpPost]
        [TypeFilter(typeof(CheckAdminAccessAttribute), Arguments = new object[] { Access.CanEditUserInfo })]
        public IActionResult EditUserInfo(EditUserInfoViewModel editUserInfoViewModel)
        {
            editUserInfoViewModel.AdminAccess = userAccessRepository.GetUserAccess(AdminUserId);
            userAccessRepository.SetUserAccess(editUserInfoViewModel);

            return RedirectToAction("Search");
        }
    }
}

MyFirstEShop/Areas/Admin/Views/UserManagement/EditUserInfo.cshtml
@model EditUserInfoViewModel

@{
    ViewData["Title"] = "EditUserAccess";
}

<div class="row p-4">
    <div class="col-12">
        <form asp-area="Admin" asp-action="EditUserInfo" asp-controller="UserManagement" class="row CForm"
            method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @if (Model.AdminAccess.Contains(Access.CanSetAdmin))
            {
                <div class="form-group form-check col-6 ">
                    <h3 class="d-inline-block">آیا آین کاربر را می خواهید <span style="color:red;">ادمین</span> کنید ؟ </h3>
                    <input asp-for="User.IsAdmin" class="form-check-input ml-2" style="display:inline-block;" />
                </div>
            }
            
            @if (Model.AdminAccess.Contains(Access.CanSetTeacher))
            {
                <div class="form-group form-check col-6">
                    <h3 class="d-inline-block">آیا آین کاربر را می خواهید <span style="color:green;">مدرس</span> کنید ؟
                    </h3>
                    <input asp-for="User.IsTeacher" class="form-check-input ml-2" style="display:inline-block;" />
                </div>
            }
            @if (Model.AdminAccess.Contains(Access.CanSetAccessForUser))
            {
                <div class="form-group col-4 pt-4" style="display: inline-block;">
                    <label class="control-label d-block">سطوح کاربر</label>
                    <select multiple asp-for="UserAccess" id="SELECT" class="d-block w-100"
                    style="font-size: larger;">
                        @foreach (var item in Enum.GetValues(typeof(Access)).Cast<Access>())
                        {
                            <option value=@((int)(item))>
                                @item.ToString()
                            </option>
                        }
                    </select>
                </div>
            }
            @if (Model.AdminAccess.Contains(Access.CanEditUserInfo))
            {
                <div class="row">
                    <div class="form-group col-12">
                        <label asp-for="User.FirstName" class="control-label"></label>
                        <input asp-for="User.FirstName" class="form-control border-bottom-blue"
                        style="font-size: x-large;" />
                        <span asp-validation-for="User.FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="User.LastName" class="control-label"></label>
                        <input asp-for="User.LastName" class="form-control border-bottom-blue"
                        style="font-size: x-large;" />
                        <span asp-validation-for="User.LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="User.Email" class="control-label"></label>
                        <input asp-for="User.Email" class="form-control border-bottom-blue" style="font-size: x-large;" />
                        <span asp-validation-for="User.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="User.Password" class="control-label"></label>
                        <input asp-for="User.Password" class="form-control border-bottom-blue"
                        style="font-size: x-large;" />
                        <span asp-validation-for="User.Password" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="User.PhoneNumber" class="control-label"></label>
                        <input asp-for="User.PhoneNumber" class="form-control border-bottom-blue"
                        style="font-size: x-large;" />
                        <span asp-validation-for="User.PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="User.VerifyEmail" class="control-label"></label>
                        <input asp-for="User.VerifyEmail" class="form-check-input ml-2" style="font-size: x-large;" />
                    </div>
                    <div class="form-group col-12">
                        <label asp-for="User.About" class="control-label"></label>
                        <textarea asp-for="User.About" class="form-control border-bottom-blue"
                        style="resize: none; height: 20vh;"></textarea>
                        <span asp-validation-for="User.About" class="text-danger"></span>
                    </div>
                </div>
            }


            <div class="form-group">
                <input class="btn btn-success" type="submit" value="ثبت" />
            </div>
            <input asp-for="User.Id" type="hidden" />
        </form>
    </div>
</div>


@section Scripts {

    <script>
        $(document).ready(function () {
            $('#SELECT').select2();
        });
    </script>
}

MyFirstEShop/Areas/Admin/Views/UserManagement/Search.cshtml
@model IEnumerable<User>

<div class="row">
    @await Component.InvokeAsync("SearchUser")
</div>

<div class="row ">
    @if (Model.Count() != 0)
    {
        <div class="col-12 table-responsive p-4">

            <table>
                <tr>
                    <th>userid</th>
                    <th>نام</th>
                    <th>نام خانوادگی</th>
                    <th>ایمیل</th>
                    <th colspan="2">شماره تلفن</th>
                    <th colspan="3">تاریخ ثبت نام</th>
                    <th>Is Admin </th>
                    <th>Is Teacher </th>
                    <th colspan="3"></th>
                </tr>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.Id</td>
                        <td>@user.FirstName</td>
                        <td>@user.LastName</td>
                        <td>@user.Email</td>
                        <td colspan="2">@user.PhoneNumber</td>
                        <td colspan="3">@user.RegisterTime</td>
                        <td>@user.IsAdmin</td>
                        <td>@user.IsTeacher</td>
                        <td colspan="3">
                            <a class="btn btn-info"  asp-area="Admin" asp-action="EditUserInfo" asp-controller="UserManagement" asp-route-userId=@user.Id>تغییر مشخصات کاربر</a>
                        </td>
                    </tr>
                }

            </table>

        </div>
    }
</div>



@section Scripts {

    <script>
        $(document).ready(function () {
            $('#SELECT').select2();
        });
    </script>
}

MyFirstEShop/Areas/Admin/Views/UserManagement/SearchUserViewComponent.cshtml
@model SearchUserViewModel


<div class="col-12 bg-White-Gradian p-4">

    <form class="CForm row" asp-area="Admin" asp-action="Result" asp-controller="UserManagement" method="get">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group col-4" style="display: inline-block;">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName"></span>
        </div>
        <div class="form-group col-4" style="display: inline-block;">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName"></span>
        </div>
        <div class="form-group col-4" style="display: inline-block;">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group col-4" style="display: inline-block;">
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber"></span>
        </div>

        <div class="form-group col-4 pt-4" style="display: inline-block;">
            <label class="control-label d-block">سطح کاربر</label>
            <select multiple asp-for="SelectedOptionsId" id="SELECT" class="d-block w-100" style="font-size: larger;">
                @foreach (var item in Model.SelectedOptions)
                {
                    <option value=@((int)(item))>
                        @item.ToString()
                    </option>
                }
            </select>
        </div>

        <div class="form-group col-4 pt-4" style="display: inline-block;">
            <input type="submit" value="جستجو" class="btn btn-success fa-pull-left" style=" width: 30%;" />
        </div>
    </form>
</div>